//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.12 at 06:20:19 PM CEST 
//


package com.tim15.model.xml.mt102;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zaglavljeKliringa" type="{}ZaglavljeMT102"/>
 *         &lt;element name="stavkeKliringa" type="{}StavkaKliringa" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zaglavljeKliringa",
    "stavkeKliringa"
})
@XmlRootElement(name = "MT102")
public class MT102 {

    @XmlElement(required = true)
    protected ZaglavljeMT102 zaglavljeKliringa;
    protected List<StavkaKliringa> stavkeKliringa;

    /**
     * Gets the value of the zaglavljeKliringa property.
     * 
     * @return
     *     possible object is
     *     {@link ZaglavljeMT102 }
     *     
     */
    public ZaglavljeMT102 getZaglavljeKliringa() {
        return zaglavljeKliringa;
    }

    /**
     * Sets the value of the zaglavljeKliringa property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZaglavljeMT102 }
     *     
     */
    public void setZaglavljeKliringa(ZaglavljeMT102 value) {
        this.zaglavljeKliringa = value;
    }

    /**
     * Gets the value of the stavkeKliringa property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stavkeKliringa property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStavkeKliringa().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StavkaKliringa }
     * 
     * 
     */
    public List<StavkaKliringa> getStavkeKliringa() {
        if (stavkeKliringa == null) {
            stavkeKliringa = new ArrayList<StavkaKliringa>();
        }
        return this.stavkeKliringa;
    }

}
