//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.13 at 03:31:34 AM CEST 
//


package com.tim15.model.xml.izvod;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="klijentId" type="{}Str20"/>
 *         &lt;element name="brojRacuna" type="{}RacunType"/>
 *         &lt;element name="datumPrometa" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="prethodnoStanje" type="{}Dec15d2"/>
 *         &lt;element name="prometUkorist" type="{}Dec15d2"/>
 *         &lt;element name="prometNaTeret" type="{}Dec15d2"/>
 *         &lt;element name="novoStanje" type="{}Dec15d2"/>
 *         &lt;element name="stavka" type="{}StavkaIzvoda" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "klijentId",
    "brojRacuna",
    "datumPrometa",
    "prethodnoStanje",
    "prometUkorist",
    "prometNaTeret",
    "novoStanje",
    "stavka"
})
@XmlRootElement(name = "Izvod")
public class Izvod {

    @XmlElement(required = true)
    protected String klijentId;
    @XmlElement(required = true)
    protected String brojRacuna;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPrometa;
    @XmlElement(required = true)
    protected BigDecimal prethodnoStanje;
    @XmlElement(required = true)
    protected BigDecimal prometUkorist;
    @XmlElement(required = true)
    protected BigDecimal prometNaTeret;
    @XmlElement(required = true)
    protected BigDecimal novoStanje;
    protected List<StavkaIzvoda> stavka;

    /**
     * Gets the value of the klijentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKlijentId() {
        return klijentId;
    }

    /**
     * Sets the value of the klijentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKlijentId(String value) {
        this.klijentId = value;
    }

    /**
     * Gets the value of the brojRacuna property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojRacuna() {
        return brojRacuna;
    }

    /**
     * Sets the value of the brojRacuna property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojRacuna(String value) {
        this.brojRacuna = value;
    }

    /**
     * Gets the value of the datumPrometa property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPrometa() {
        return datumPrometa;
    }

    /**
     * Sets the value of the datumPrometa property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPrometa(XMLGregorianCalendar value) {
        this.datumPrometa = value;
    }

    /**
     * Gets the value of the prethodnoStanje property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrethodnoStanje() {
        return prethodnoStanje;
    }

    /**
     * Sets the value of the prethodnoStanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrethodnoStanje(BigDecimal value) {
        this.prethodnoStanje = value;
    }

    /**
     * Gets the value of the prometUkorist property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrometUkorist() {
        return prometUkorist;
    }

    /**
     * Sets the value of the prometUkorist property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrometUkorist(BigDecimal value) {
        this.prometUkorist = value;
    }

    /**
     * Gets the value of the prometNaTeret property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrometNaTeret() {
        return prometNaTeret;
    }

    /**
     * Sets the value of the prometNaTeret property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrometNaTeret(BigDecimal value) {
        this.prometNaTeret = value;
    }

    /**
     * Gets the value of the novoStanje property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNovoStanje() {
        return novoStanje;
    }

    /**
     * Sets the value of the novoStanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNovoStanje(BigDecimal value) {
        this.novoStanje = value;
    }

    /**
     * Gets the value of the stavka property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stavka property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStavka().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StavkaIzvoda }
     * 
     * 
     */
    public List<StavkaIzvoda> getStavka() {
        if (stavka == null) {
            stavka = new ArrayList<StavkaIzvoda>();
        }
        return this.stavka;
    }

}
